### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Butonix** [antiSocialNet/antiSocial#20]
npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm WARN deprecated coffee-script@1.10.0: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rever\AppData\Roaming\npm-cache\_logs\2017-12-16T13_53_08_071Z-debug.log

**Comment by mediapolis** [comment]
This project loads some modules via git so `npm install` is dependent git being installed

```
Please check if you have git installed and in your PATH.
```
