### ISSUE TITLE
Should a node be at all http accessible ? 

### ISSUE THREAD

**Issue by tevans62** [antiSocialNet/antiSocial#208]
### Issue details

Accidentally went to ae.myantisocial.net without https and it worked. 

The browser warned me as I entered my password but seems like a redirect to https would be better. 
### Affected platforms

- [ ] Server Side Issue

or Client Side Browser
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by mediapolis** [comment]
The current service platform  is now Pure SSL - no  http listener at all.

We are trying to be agnostic to serving method:
  Docker on a  real server or virtual instance
  Managed container service behind a load balancer
  Clustered for larger scale communities

Each scheme would need it's own method to bounce from http to https

#232
