### ISSUE TITLE
Unstable touch gesture support when liking/reacting to a post on Android

### ISSUE THREAD

**Issue by bibiali99** [antiSocialNet/antiSocial#222]
### Issue details

Not clear how to react to a post when using touch gesture. I tried click down and hold to open the reactions popup but there seems to be a delay in showing popup followed by auto-selection of the thumbs up.  Upon clicking again on the like button nothing happens. 

### Steps to reproduce

Using chrome on Android, open myantisocial site
Find a post or create one
Try long press on the reaction button 👍🏻
Notice that sometimes the popup either opens late or disappears before you select your reaction.
Notice that even if you correctly select a reaction pressing and holding on button again to change reaction is also not as expected.

Expected on hold+press to see popup persist until I press on a reaction. I may not be using it correctly.  Please advise in that case.

### Affected platforms

Chrome 65.0.3325.109 on Android 8.1.0 Pixel 2

- [ ] Server Side Issue

or Client Side Browser
- [x ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by mediapolis** [comment]
Touch not optimal at the moment. In touch it should be changed to behave as follows:

- [ ] tap anywhere in zone - reveal menu of reactions. Tap on specific reaction to select or outside region to dismiss.
