### ISSUE TITLE
Empty post in my feed

### ISSUE THREAD

**Issue by bibiali99** [antiSocialNet/antiSocial#223]
### Issue details

Looking at my feed sorted by activity, I see an empty post card as shown in the screenshot.  This was between Alan's posts and the beginning of my activity.

### Steps to reproduce

Don't know how this empty post was created.

### Affected platforms

Chrome 65.0.3325.109 on Android 8.1.0 Pixel 2

- [ ] Server Side Issue

or Client Side Browser
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

https://photos.app.goo.gl/A6JjdcViE1S3x9V22

**Comment by mediapolis** [comment]
Permission issue:

When someone who is not a friend of mine posts on the wall of a friend of mine I can't load that post. 

#168 will include logic to grant access by 'tagging'
