### ISSUE TITLE
Article doesn't show OG:image tag, does on FB

### ISSUE THREAD

**Issue by bajan64** [antiSocialNet/antiSocial#224]
https://www.lgbtqnation.com/2018/04/hot-blooded-heterosexual-claims-pain-meds-turned-gay/?utm_source=notification&utm_medium=push&utm_campaign=onesignal

**Comment by mediapolis** [comment]
client side:

function OgTagPreview(elem, options) {

data.result.ogData.data not defined (site has no OG support?)

throwing error:

var site = data.result.ogData.data.ogSiteName ? data.result.ogData.data.ogSiteName : parseUri(self.url).host;

Client side preview controller needs to be tolerant of bad OG

This particular link is failing on call to scrape OG with a 404 which must be related to soething that are doing with user agent or cookies.

**Comment by mediapolis** [comment]
really slow site. increased timeout on og scrape
