### ISSUE TITLE
Error popup on loading my feed when feed has an article from businessInsider

### ISSUE THREAD

**Issue by bibiali99** [antiSocialNet/antiSocial#228]
### Issue details

Today I am seeing a popup with error "502 bad gateway" when I load my feed.

### Steps to reproduce

1. For some reason this doesn't happen when I have devtools open. So make sure you close your devtools on Chrome if you have it open.
2. Load a feed with Alan's feed like this page https://ae.myantisocial.net/feed#
3. Notice an error popup (screenshot)

devtools console shows:
```
Failed to load resource: the server responded with a status of 502 ()
https://ae.myantisocial.net/api/OgTags/scrape?url=https%3A%2F%2Fwww.businessinsider.com.au%2Frare-earth-minerals-found-in-japan-2018-4%3Fr%3DUS%26IR%3DT
```

### Affected platforms

This happens when I'm on my mobile  (Android Chrome) or desktop at work over http-proxy (Windows Chrome)

- [ ] Server Side Issue

or Client Side Browser
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

[Screenshot of issue](https://photos.app.goo.gl/O2NYNjrmAfdAntAm1)

**Comment by mediapolis** [comment]
issue with load balancer. resolved.
