### ISSUE TITLE
I see option to Edit someone else's comment to my post when I am tagged.

### ISSUE THREAD

**Issue by bibiali99** [antiSocialNet/antiSocial#229]
### Issue details

When looking at comments/replies to a post I made, and when clicking on the comment/reply action button for comment made by a friend who tagged me, the menu offers me the choice to Edit/Delete this friend's comment/reply.  If I actually try to edit, it fails.
EDIT: This could be happening only when I am tagged in a comment by a friend.

### Steps to reproduce

When clicking on the action button in the comment/reply made by someone else to my post, the menu offers me the choice to Edit the comment.

1. Go to any post you have that has comments from friends
2. Click on the action (kabob) button for a comment made by a friend. (I think you need to be tagged in the comment)
3. The action menu shows "edit", "delete" and "hide", click on edit (I didn't want to delete so I was afraid to test that)
4. Notice the editor popup shows but no textarea and many JS errors in the console.

### Affected platforms

- [ ] Server Side Issue

or Client Side Browser
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

### Screenshots / Screencast (Optional)

[Screenshot of the issue](https://photos.app.goo.gl/EBJJPHUiIOmoB3pi2)

**Comment by mediapolis** [comment]
Similar to other permission issue. When someone posts on your wall a "share" is created in your DB.

- [ ] make edit button aware of this condition, disallowing edit.
- [ ] make delete button aware of this condition, deleting share only.
