### ISSUE TITLE
URL preview "Page Not Found"

### ISSUE THREAD

**Issue by bajan64** [antiSocialNet/antiSocial#234]
http://www.dispatch.com/news/20180421/bezos-support-for-lgbt-community-may-be-part-of-amazons-search-for-new-home

**Comment by mediapolis** [comment]
Server not providing content type for OG image

HTTP/1.1 304 Not Modified
Accept-Ranges: bytes
Age: 65
Cache-Control: s-max-age=600, max-age=600, must-revalidate, proxy-revalidate
Date: Mon, 23 Apr 2018 20:11:08 GMT
Last-Modified: Sat, 21 Apr 2018 20:14:28 GMT
ServedBy: gm2-d-web-29.gmi.loc
Server: Microsoft-IIS/7.5
X-Cache: HIT-Varnish
X-Cache-Hits: 1
X-Powered-By: ASP.NET
X-Served-By: ip-172-28-141-57.gmi.loc
x-stale: true
X-UA-Device: pc
X-Varnish: 483573280 483551770
X-Varnish-beresp-grace: 43200.000
X-Varnish-beresp-status: 200
X-Varnish-beresp-ttl: 600.000
Connection: keep-alive
X-Iinfo: 3-2542214-2546767 NNNN CT(0 -1 0) RT(1524511341668 65414) q(0 0 0 -1) r(1 1) U5
X-CDN: Incapsula

upload.js failing when we try to cache the image:

if (response.statusCode === 200 && response.headers['content-type'] && response.headers['content-type'].match(/^image\//)) {

**Comment by bajan64** [comment]
https://www.airvuz.com/video/Burning-Man--Spirit-and-Soul---Inspire-2-X5S-4K?id=5aca3dbd65fb60784c4948ab

**Comment by bajan64** [comment]
https://www.themarshallproject.org/2018/04/19/framed-for-murder-by-his-own-dna

**Comment by mediapolis** [comment]
fixed

**Comment by bajan64** [comment]
http://astronomy.com/news/2018/04/the-milky-ways-supermassive-black-hole-has-siblings?spMailingID=34155495&spUserID=NjkzMTI1MTE4MzE2S0&spJobID=1280456767&spReportId=MTI4MDQ1Njc2NwS2

**Comment by mediapolis** [comment]
Worked in preview, not after post.

Fixed once db entry cleared for OgTag. 

- [ ] Examine negative cache scenario (ttl?)

- [ ] Is the URL used in the preview the same as the one used after post?
