### ISSUE TITLE
Tried to share post, get Javascript error

### ISSUE THREAD

**Issue by bajan64** [antiSocialNet/antiSocial#259]
### Issue details
Share from top right menu fails on JavaScript error.

### Steps to reproduce
https://ae.myantisocial.net/mr/post/7a022aa8-418b-44c1-a710-84b0497aa1ae

raven.js:364 Uncaught TypeError: Cannot read property 'top' of undefined
    at scrollToElement (DigitopiaSocial.js:66113)
    at HTMLAnchorElement.<anonymous> (DigitopiaSocial.js:67815)
    at HTMLDivElement.dispatch (jquery.min.js:2)
    at HTMLDivElement.y.handle (jquery.min.js:2)
    at HTMLDivElement.d (raven.js:360)

### Affected platforms

- [ ] Server Side Issue

or Client Side Browser
- [X ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by mediapolis** [comment]
The permalink page does not have a posting form. Not quite sure what to do about that… Makes sense that one would want to share from there but would need to embed a form or do it in a popup or switch to the poster’s page.
