### ISSUE TITLE
Comment duplicated, liking one likes both

### ISSUE THREAD

**Issue by bajan64** [antiSocialNet/antiSocial#267]
https://ae.myantisocial.net/bajan64/post/07b8f7c7-7fc5-4cd9-a479-e001b0e51a28

### Affected platforms

- [ ] Server Side Issue

or Client Side Browser
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by mediapolis** [comment]
https://mr.myantisocial.net/bajan64/post/459e1ca9-83e5-484e-9bc2-9039cd517508.json

Must somehow be 2 websocket listeners.

**Comment by mediapolis** [comment]
May be fixed with full-duplex websockets
