### ISSUE TITLE
Persistent menu 

### ISSUE THREAD

**Issue by jadiknight** [antiSocialNet/antiSocial#362]
### Issue details

 Android 8.0.0 when clicking on the top left menu, I can't get rid of it no matter what I do next. It just stays there. 

### Affected platforms

- [ ] Server Side Issue

or Client Side Browser
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Other

**Comment by mediapolis** [comment]
Hello.

There is a known issue where the menu if triggered while **logged out** causes it to be stuck open. Is this what you are experiencing or does this also happen when logged in?

Thanks.

**Comment by jadiknight** [comment]
I was initially logged in, then accidentally clicked the back button, which
reverted me to the login page. For some reason, the forward button didn't
work, so I input my login parameters again. And that is when it happened. I
hope this helps.

**Comment by mediapolis** [comment]
dupe #357
